services:
  web:
    container_name: bangkok_railway_json
    build: .
    restart: unless-stopped
    ports:
      - "7003:80"                    
    volumes:
      - .:/app                       
    environment:
      - PYTHONPATH=/app         
    networks:
      - app-network
  
networks:
  app-network:
    driver: bridge

