services:
  backend:
    container_name: bangkok_transit
    build:
      context: .
    restart: unless-stopped
    ports:
      - "7003:80"
    environment:
      - PYTHONPATH=/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
